version: "3.1"
services:
  giri-marketing-api:
    image: 736483926068.dkr.ecr.eu-west-2.amazonaws.com/girii/marketingportalapi:20210310.1
    ports:
      - 21000:80
    networks:
      - backend
  giri-multimedia-api:
    image: 736483926068.dkr.ecr.eu-west-2.amazonaws.com/girii/multimediaapi:20210310.1
    ports:
      - 21001:80
    networks:
      - backend

  giri-marketing-client:
    image: 736483926068.dkr.ecr.eu-west-2.amazonaws.com/girii/marketingportalclient:20210309.10
    ports:
      - 4200:80
    networks:
      - frontend

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:
